fun-with-jenkins2
flugel-it/fun-with-jenkins2 pull request #1
Opened 2017-12-16 15:39 UTC by barbosacisco

Changes were made in the README.md file, adding the instructions to install Docker in Ubuntu 16.4 and in the Script files in the directory /scripts.

2017-12-19 15:54 UTC, diegows requested changes
Documentation looks ok. Only remove what you added on the scripts, because those scripts are supposed to be called by Jenkins to build and deploy an application, but not jenkins by itself.

2017-12-27 13:53 UTC, barbosacisco commented
Hello Diego, here goes the PR with the Ansible playbook to provision a VPS in Amazon AWS running Jenkins in a docker container. I added the documentation related to it in README.md.

2017-12-31 23:40 UTC, barbosacisco commented
Hello Diego, I sent another PR where I got the Documentation better organized.

2018-01-03 15:33 UTC, diegows approved these changes

2018-01-03 15:34 UTC, merged