Vagrant test
flugel-it/fun-with-jenkins2 pull request #7
Opened 2018-07-12 21:24 UTC by jamalpica

Adding Vagrant support via Digital Ocean

2018-07-16 22:48 UTC, diegows requested changes
Can we use virtualbox instead of DO?

2018-07-17 01:03 UTC, jamalpica commented
Sure! no problem. 

I'm changing all necessary files in order to keep all working properly!

2018-07-17 01:30 UTC, jamalpica commented
Fixed as you requested! 
Added Virtualbox support instead of DigitalOcean.

2018-07-17 17:59 UTC, diegows approved these changes

2018-07-17 17:59 UTC, merged